### ISSUE TITLE
Verge thinks an element exactly off of the screen is in the viewport

### ISSUE THREAD

**Issue by yuchant** [ryanve/verge#18]
Hey Ryan,

Thanks for building this awesome plugin! My current viewport plugin fails on iOS so this is fantastic. The main difference I see is that Verge thinks an element that is exactly off of the screen is in the viewport.

Imagine a drawer with the following CSS:

	.drawer {
		position: fixed;
		right: -300px;
		width: 300px;
		top: 0;
		bottom: 0;
	}

A thought experiment: a `1px` wide fixed position element with `right: 0` sits exactly on the right edge. Setting the `right` parameter to `-1px` puts it exactly off the screen.

Any thoughts?

Thank you!

**Comment by ryanve** [comment]
Thanks @yuchant! It seems to be due to the scrollbar. [CSS considers the scrollbar to be in the viewport](http://www.w3.org/TR/css3-mediaqueries/#width). That explains why `left: -300px` is in the viewport but `right: -300px` isn't. It's weird that switching to `position: absolute` changes the result though, isn't it? To be safe you could add extra space like `right: -320px` or use `verge.inViewport(drawer, -20)` to be sure it's at least `20px` in the viewport. Or workaround the issue by transitioning `width` rather than `right` like

```css
.drawer {
  position: fixed;
  width: 300px;
  right: 0;
  top: 0;
  bottom: 0;
  transition: width .2s ease-in-out;
}

.drawer.is-offscreen {
  width: 0;
  overflow: hidden;
}
